# Generated by Django 3.2.7 on 2021-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_img',
            field=models.ImageField(default=1, upload_to='hotel_img'),
            preserve_default=False,
        ),
    ]
