# Generated by Django 3.2.7 on 2021-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotel_hotel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
